[package]
name = "niri-helper"
version = "0.1.2"
edition = "2021"

[dependencies]
serde_json = "1.0.133"
niri-ipc = "25.11.0"
toml = "0.9.5"
regex = "1.11.1"
serde = "1.0.214"
clap = { version = "4.5.21", features = ["derive"] }
